FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app and pre-trained model only
COPY ./app ./app

# Copy source
COPY . .

# Expose dev port
EXPOSE 8101
ENV ENV=development

# Start the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8101"]